### PR TITLE
Support all Rails 5 releases

### PR DESCRIPTION
**Pull request by pedantic-git**
This plugin works fine for Rails 5.1 - here's a PR that relaxes the version constraint to support all of 5.x.

### CODE REVIEW

**Comment by picandocodigo** [comment]
Hi @pedantic-git thanks for the PR and sorry it took so long to merge it. I hadn't even seen the second commit with the Rubocop fixes!

**Comment by pedantic-git** [comment]
No worries at all! Thanks for merging!

**Comment by thebenedict** [comment]
Much appreciated! @picandocodigo Any chance you'd be willing to publish the latest version to rubygems?

**Comment by picandocodigo** [comment]
@thebenedict just bumped the version in rubygems. Let me know if it all works fine for you. Thanks!

**Comment by thebenedict** [comment]
@picandocodigo Works great, many thanks!

**Pull request merged**
